import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { anton, ibmplex, opensans, barlowCondensed } from "@/config/fonts";
import { Toaster } from "sonner";
import LocomotiveScrollWrapper from "@/components/LocomotiveScrollWrapper";
import NavbarWrapper from "@/components/NavbarWrapper";
import FooterWrapper from "@/components/FooterWrapper";
import { ThemeProvider } from "@/app/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={barlowCondensed.variable}
    >
      <body
        className={`${geistSans.variable} ${ibmplex.variable} ${anton.variable} ${opensans.variable} antialiased bg-neutral-100`}
      >
        <ThemeProvider>
          <NavbarWrapper />
          <LocomotiveScrollWrapper>
            {children}
            <FooterWrapper />
          </LocomotiveScrollWrapper>
          <Toaster
            richColors
            position='bottom-right'
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
